### ISSUE TITLE
Convert Tokenizer Test to Table Driven Testing

### ISSUE THREAD

**Issue by phoenixcoder** [bio-pdv/tools#4]
[Code to Convert](https://github.com/bio-pdv/tools/blob/a4403565299d525f803310a0b1633cf100a977cd/gene/cmd/parse/tokenizer_test.go#L193-L274)

[Here's an example of table driven testing.](https://github.com/lisa-phoenix-dev/pop-dyn-viewer-prototype/blob/f8112ec5368e406efa5a39bd4d06c7998332b244/server/service/server_test.go#L73-L101)

**Comment by kimlisa** [comment]
**Articles on table driven:**
https://dave.cheney.net/2019/05/07/prefer-table-driven-tests
